//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appleseed.WebApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthHeader", Namespace="http://schemas.datacontract.org/2004/07/Appleseed.Services.Web.Api")]
    [System.SerializableAttribute()]
    public partial class AuthHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APIKey {
            get {
                return this.APIKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.APIKeyField, value) != true)) {
                    this.APIKeyField = value;
                    this.RaisePropertyChanged("APIKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Appleseed.Services.Web.Api.Entity")]
    [System.SerializableAttribute()]
    public partial class Role : Appleseed.WebApi.BaseEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Appleseed.Services.Web.Api.Entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Appleseed.WebApi.Role))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UniqueGUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UniqueGUID {
            get {
                return this.UniqueGUIDField;
            }
            set {
                if ((this.UniqueGUIDField.Equals(value) != true)) {
                    this.UniqueGUIDField = value;
                    this.RaisePropertyChanged("UniqueGUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Appleseed.WebApi.IPortalServices")]
    public interface IPortalServices {
        
        // CODEGEN: Generating message contract since message ValidateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/ValidateUser", ReplyAction="http://tempuri.org/IPortalServices/ValidateUserResponse")]
        Appleseed.WebApi.ValidateUserResponse ValidateUser(Appleseed.WebApi.ValidateUserRequest request);
        
        // CODEGEN: Generating message contract since message GetUsersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetUsers", ReplyAction="http://tempuri.org/IPortalServices/GetUsersResponse")]
        Appleseed.WebApi.GetUsersResponse GetUsers(Appleseed.WebApi.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since message GetRolesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetRoles", ReplyAction="http://tempuri.org/IPortalServices/GetRolesResponse")]
        Appleseed.WebApi.GetRolesResponse GetRoles(Appleseed.WebApi.GetRolesRequest request);
        
        // CODEGEN: Generating message contract since message CreateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/CreateUser", ReplyAction="http://tempuri.org/IPortalServices/CreateUserResponse")]
        Appleseed.WebApi.CreateUserResponse CreateUser(Appleseed.WebApi.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since message CreateRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/CreateRole", ReplyAction="http://tempuri.org/IPortalServices/CreateRoleResponse")]
        Appleseed.WebApi.CreateRoleResponse CreateRole(Appleseed.WebApi.CreateRoleRequest request);
        
        // CODEGEN: Generating message contract since message AddUserToRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/AddUserToRole", ReplyAction="http://tempuri.org/IPortalServices/AddUserToRoleResponse")]
        Appleseed.WebApi.AddUserToRoleResponse AddUserToRole(Appleseed.WebApi.AddUserToRoleRequest request);
        
        // CODEGEN: Generating message contract since message RemoveUserFromRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/RemoveUserFromRole", ReplyAction="http://tempuri.org/IPortalServices/RemoveUserFromRoleResponse")]
        Appleseed.WebApi.RemoveUserFromRoleResponse RemoveUserFromRole(Appleseed.WebApi.RemoveUserFromRoleRequest request);
        
        // CODEGEN: Generating message contract since message AddUserToPortalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/AddUserToPortal", ReplyAction="http://tempuri.org/IPortalServices/AddUserToPortalResponse")]
        Appleseed.WebApi.AddUserToPortalResponse AddUserToPortal(Appleseed.WebApi.AddUserToPortalRequest request);
        
        // CODEGEN: Generating message contract since message RemoveUserFromPortalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/RemoveUserFromPortal", ReplyAction="http://tempuri.org/IPortalServices/RemoveUserFromPortalResponse")]
        Appleseed.WebApi.RemoveUserFromPortalResponse RemoveUserFromPortal(Appleseed.WebApi.RemoveUserFromPortalRequest request);
        
        // CODEGEN: Generating message contract since message GetPagesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetPages", ReplyAction="http://tempuri.org/IPortalServices/GetPagesResponse")]
        Appleseed.WebApi.GetPagesResponse GetPages(Appleseed.WebApi.GetPagesRequest request);
        
        // CODEGEN: Generating message contract since message CreatePageInPortalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/CreatePageInPortal", ReplyAction="http://tempuri.org/IPortalServices/CreatePageInPortalResponse")]
        Appleseed.WebApi.CreatePageInPortalResponse CreatePageInPortal(Appleseed.WebApi.CreatePageInPortalRequest request);
        
        // CODEGEN: Generating message contract since message GetModulesOnPageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetModulesOnPage", ReplyAction="http://tempuri.org/IPortalServices/GetModulesOnPageResponse")]
        Appleseed.WebApi.GetModulesOnPageResponse GetModulesOnPage(Appleseed.WebApi.GetModulesOnPageRequest request);
        
        // CODEGEN: Generating message contract since message GetAllInstalledModulesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetAllInstalledModules", ReplyAction="http://tempuri.org/IPortalServices/GetAllInstalledModulesResponse")]
        Appleseed.WebApi.GetAllInstalledModulesResponse GetAllInstalledModules(Appleseed.WebApi.GetAllInstalledModulesRequest request);
        
        // CODEGEN: Generating message contract since message UnInstallModuleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/UnInstallModule", ReplyAction="http://tempuri.org/IPortalServices/UnInstallModuleResponse")]
        Appleseed.WebApi.UnInstallModuleResponse UnInstallModule(Appleseed.WebApi.UnInstallModuleRequest request);
        
        // CODEGEN: Generating message contract since message AddModuleToPageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/AddModuleToPage", ReplyAction="http://tempuri.org/IPortalServices/AddModuleToPageResponse")]
        Appleseed.WebApi.AddModuleToPageResponse AddModuleToPage(Appleseed.WebApi.AddModuleToPageRequest request);
        
        // CODEGEN: Generating message contract since message UpdateModuleInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/UpdateModuleInfo", ReplyAction="http://tempuri.org/IPortalServices/UpdateModuleInfoResponse")]
        Appleseed.WebApi.UpdateModuleInfoResponse UpdateModuleInfo(Appleseed.WebApi.UpdateModuleInfoRequest request);
        
        // CODEGEN: Generating message contract since message EditModuleDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/EditModuleData", ReplyAction="http://tempuri.org/IPortalServices/EditModuleDataResponse")]
        Appleseed.WebApi.EditModuleDataResponse EditModuleData(Appleseed.WebApi.EditModuleDataRequest request);
        
        // CODEGEN: Generating message contract since message GetPortalsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/GetPortals", ReplyAction="http://tempuri.org/IPortalServices/GetPortalsResponse")]
        Appleseed.WebApi.GetPortalsResponse GetPortals(Appleseed.WebApi.GetPortalsRequest request);
        
        // CODEGEN: Generating message contract since message CreatePortalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/CreatePortal", ReplyAction="http://tempuri.org/IPortalServices/CreatePortalResponse")]
        Appleseed.WebApi.CreatePortalResponse CreatePortal(Appleseed.WebApi.CreatePortalRequest request);
        
        // CODEGEN: Generating message contract since message ChangePortalSettingsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/ChangePortalSettings", ReplyAction="http://tempuri.org/IPortalServices/ChangePortalSettingsResponse")]
        Appleseed.WebApi.ChangePortalSettingsResponse ChangePortalSettings(Appleseed.WebApi.ChangePortalSettingsRequest request);
        
        // CODEGEN: Generating message contract since message RemovePortalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortalServices/RemovePortal", ReplyAction="http://tempuri.org/IPortalServices/RemovePortalResponse")]
        Appleseed.WebApi.RemovePortalResponse RemovePortal(Appleseed.WebApi.RemovePortalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public ValidateUserRequest() {
        }
        
        public ValidateUserRequest(Appleseed.WebApi.AuthHeader AuthHeader, string username, string password) {
            this.AuthHeader = AuthHeader;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponse() {
        }
        
        public ValidateUserResponse(bool ValidateUserResult) {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersResponse {
        
        public GetUsersResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRolesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetRolesRequest() {
        }
        
        public GetRolesRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRolesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Appleseed.WebApi.Role> GetRolesResult;
        
        public GetRolesResponse() {
        }
        
        public GetRolesResponse(System.Collections.Generic.List<Appleseed.WebApi.Role> GetRolesResult) {
            this.GetRolesResult = GetRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserResponse {
        
        public CreateUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public CreateRoleRequest() {
        }
        
        public CreateRoleRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateRoleResponse {
        
        public CreateRoleResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public AddUserToRoleRequest() {
        }
        
        public AddUserToRoleRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToRoleResponse {
        
        public AddUserToRoleResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public RemoveUserFromRoleRequest() {
        }
        
        public RemoveUserFromRoleRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromRoleResponse {
        
        public RemoveUserFromRoleResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToPortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToPortalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public AddUserToPortalRequest() {
        }
        
        public AddUserToPortalRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserToPortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserToPortalResponse {
        
        public AddUserToPortalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromPortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromPortalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public RemoveUserFromPortalRequest() {
        }
        
        public RemoveUserFromPortalRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveUserFromPortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveUserFromPortalResponse {
        
        public RemoveUserFromPortalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetPagesRequest() {
        }
        
        public GetPagesRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPagesResponse {
        
        public GetPagesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePageInPortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePageInPortalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public CreatePageInPortalRequest() {
        }
        
        public CreatePageInPortalRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePageInPortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePageInPortalResponse {
        
        public CreatePageInPortalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModulesOnPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModulesOnPageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetModulesOnPageRequest() {
        }
        
        public GetModulesOnPageRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModulesOnPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetModulesOnPageResponse {
        
        public GetModulesOnPageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllInstalledModules", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllInstalledModulesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetAllInstalledModulesRequest() {
        }
        
        public GetAllInstalledModulesRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllInstalledModulesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllInstalledModulesResponse {
        
        public GetAllInstalledModulesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnInstallModule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UnInstallModuleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public UnInstallModuleRequest() {
        }
        
        public UnInstallModuleRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnInstallModuleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UnInstallModuleResponse {
        
        public UnInstallModuleResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModuleToPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModuleToPageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public AddModuleToPageRequest() {
        }
        
        public AddModuleToPageRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddModuleToPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddModuleToPageResponse {
        
        public AddModuleToPageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateModuleInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateModuleInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public UpdateModuleInfoRequest() {
        }
        
        public UpdateModuleInfoRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateModuleInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateModuleInfoResponse {
        
        public UpdateModuleInfoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditModuleData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditModuleDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public EditModuleDataRequest() {
        }
        
        public EditModuleDataRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditModuleDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditModuleDataResponse {
        
        public EditModuleDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPortals", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPortalsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public GetPortalsRequest() {
        }
        
        public GetPortalsRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPortalsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPortalsResponse {
        
        public GetPortalsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePortalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public CreatePortalRequest() {
        }
        
        public CreatePortalRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreatePortalResponse {
        
        public CreatePortalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePortalSettings", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePortalSettingsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public ChangePortalSettingsRequest() {
        }
        
        public ChangePortalSettingsRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePortalSettingsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePortalSettingsResponse {
        
        public ChangePortalSettingsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemovePortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemovePortalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Appleseed.WebApi.AuthHeader AuthHeader;
        
        public RemovePortalRequest() {
        }
        
        public RemovePortalRequest(Appleseed.WebApi.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemovePortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemovePortalResponse {
        
        public RemovePortalResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalServicesChannel : Appleseed.WebApi.IPortalServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalServicesClient : System.ServiceModel.ClientBase<Appleseed.WebApi.IPortalServices>, Appleseed.WebApi.IPortalServices {
        
        public PortalServicesClient() {
        }
        
        public PortalServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.ValidateUserResponse Appleseed.WebApi.IPortalServices.ValidateUser(Appleseed.WebApi.ValidateUserRequest request) {
            return base.Channel.ValidateUser(request);
        }
        
        public bool ValidateUser(Appleseed.WebApi.AuthHeader AuthHeader, string username, string password) {
            Appleseed.WebApi.ValidateUserRequest inValue = new Appleseed.WebApi.ValidateUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.username = username;
            inValue.password = password;
            Appleseed.WebApi.ValidateUserResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).ValidateUser(inValue);
            return retVal.ValidateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetUsersResponse Appleseed.WebApi.IPortalServices.GetUsers(Appleseed.WebApi.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public void GetUsers(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetUsersRequest inValue = new Appleseed.WebApi.GetUsersRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetUsersResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetRolesResponse Appleseed.WebApi.IPortalServices.GetRoles(Appleseed.WebApi.GetRolesRequest request) {
            return base.Channel.GetRoles(request);
        }
        
        public System.Collections.Generic.List<Appleseed.WebApi.Role> GetRoles(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetRolesRequest inValue = new Appleseed.WebApi.GetRolesRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetRolesResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetRoles(inValue);
            return retVal.GetRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.CreateUserResponse Appleseed.WebApi.IPortalServices.CreateUser(Appleseed.WebApi.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public void CreateUser(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.CreateUserRequest inValue = new Appleseed.WebApi.CreateUserRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.CreateUserResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).CreateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.CreateRoleResponse Appleseed.WebApi.IPortalServices.CreateRole(Appleseed.WebApi.CreateRoleRequest request) {
            return base.Channel.CreateRole(request);
        }
        
        public void CreateRole(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.CreateRoleRequest inValue = new Appleseed.WebApi.CreateRoleRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.CreateRoleResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).CreateRole(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.AddUserToRoleResponse Appleseed.WebApi.IPortalServices.AddUserToRole(Appleseed.WebApi.AddUserToRoleRequest request) {
            return base.Channel.AddUserToRole(request);
        }
        
        public void AddUserToRole(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.AddUserToRoleRequest inValue = new Appleseed.WebApi.AddUserToRoleRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.AddUserToRoleResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).AddUserToRole(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.RemoveUserFromRoleResponse Appleseed.WebApi.IPortalServices.RemoveUserFromRole(Appleseed.WebApi.RemoveUserFromRoleRequest request) {
            return base.Channel.RemoveUserFromRole(request);
        }
        
        public void RemoveUserFromRole(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.RemoveUserFromRoleRequest inValue = new Appleseed.WebApi.RemoveUserFromRoleRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.RemoveUserFromRoleResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).RemoveUserFromRole(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.AddUserToPortalResponse Appleseed.WebApi.IPortalServices.AddUserToPortal(Appleseed.WebApi.AddUserToPortalRequest request) {
            return base.Channel.AddUserToPortal(request);
        }
        
        public void AddUserToPortal(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.AddUserToPortalRequest inValue = new Appleseed.WebApi.AddUserToPortalRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.AddUserToPortalResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).AddUserToPortal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.RemoveUserFromPortalResponse Appleseed.WebApi.IPortalServices.RemoveUserFromPortal(Appleseed.WebApi.RemoveUserFromPortalRequest request) {
            return base.Channel.RemoveUserFromPortal(request);
        }
        
        public void RemoveUserFromPortal(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.RemoveUserFromPortalRequest inValue = new Appleseed.WebApi.RemoveUserFromPortalRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.RemoveUserFromPortalResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).RemoveUserFromPortal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetPagesResponse Appleseed.WebApi.IPortalServices.GetPages(Appleseed.WebApi.GetPagesRequest request) {
            return base.Channel.GetPages(request);
        }
        
        public void GetPages(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetPagesRequest inValue = new Appleseed.WebApi.GetPagesRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetPagesResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetPages(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.CreatePageInPortalResponse Appleseed.WebApi.IPortalServices.CreatePageInPortal(Appleseed.WebApi.CreatePageInPortalRequest request) {
            return base.Channel.CreatePageInPortal(request);
        }
        
        public void CreatePageInPortal(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.CreatePageInPortalRequest inValue = new Appleseed.WebApi.CreatePageInPortalRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.CreatePageInPortalResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).CreatePageInPortal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetModulesOnPageResponse Appleseed.WebApi.IPortalServices.GetModulesOnPage(Appleseed.WebApi.GetModulesOnPageRequest request) {
            return base.Channel.GetModulesOnPage(request);
        }
        
        public void GetModulesOnPage(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetModulesOnPageRequest inValue = new Appleseed.WebApi.GetModulesOnPageRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetModulesOnPageResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetModulesOnPage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetAllInstalledModulesResponse Appleseed.WebApi.IPortalServices.GetAllInstalledModules(Appleseed.WebApi.GetAllInstalledModulesRequest request) {
            return base.Channel.GetAllInstalledModules(request);
        }
        
        public void GetAllInstalledModules(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetAllInstalledModulesRequest inValue = new Appleseed.WebApi.GetAllInstalledModulesRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetAllInstalledModulesResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetAllInstalledModules(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.UnInstallModuleResponse Appleseed.WebApi.IPortalServices.UnInstallModule(Appleseed.WebApi.UnInstallModuleRequest request) {
            return base.Channel.UnInstallModule(request);
        }
        
        public void UnInstallModule(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.UnInstallModuleRequest inValue = new Appleseed.WebApi.UnInstallModuleRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.UnInstallModuleResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).UnInstallModule(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.AddModuleToPageResponse Appleseed.WebApi.IPortalServices.AddModuleToPage(Appleseed.WebApi.AddModuleToPageRequest request) {
            return base.Channel.AddModuleToPage(request);
        }
        
        public void AddModuleToPage(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.AddModuleToPageRequest inValue = new Appleseed.WebApi.AddModuleToPageRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.AddModuleToPageResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).AddModuleToPage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.UpdateModuleInfoResponse Appleseed.WebApi.IPortalServices.UpdateModuleInfo(Appleseed.WebApi.UpdateModuleInfoRequest request) {
            return base.Channel.UpdateModuleInfo(request);
        }
        
        public void UpdateModuleInfo(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.UpdateModuleInfoRequest inValue = new Appleseed.WebApi.UpdateModuleInfoRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.UpdateModuleInfoResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).UpdateModuleInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.EditModuleDataResponse Appleseed.WebApi.IPortalServices.EditModuleData(Appleseed.WebApi.EditModuleDataRequest request) {
            return base.Channel.EditModuleData(request);
        }
        
        public void EditModuleData(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.EditModuleDataRequest inValue = new Appleseed.WebApi.EditModuleDataRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.EditModuleDataResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).EditModuleData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.GetPortalsResponse Appleseed.WebApi.IPortalServices.GetPortals(Appleseed.WebApi.GetPortalsRequest request) {
            return base.Channel.GetPortals(request);
        }
        
        public void GetPortals(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.GetPortalsRequest inValue = new Appleseed.WebApi.GetPortalsRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.GetPortalsResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).GetPortals(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.CreatePortalResponse Appleseed.WebApi.IPortalServices.CreatePortal(Appleseed.WebApi.CreatePortalRequest request) {
            return base.Channel.CreatePortal(request);
        }
        
        public void CreatePortal(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.CreatePortalRequest inValue = new Appleseed.WebApi.CreatePortalRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.CreatePortalResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).CreatePortal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.ChangePortalSettingsResponse Appleseed.WebApi.IPortalServices.ChangePortalSettings(Appleseed.WebApi.ChangePortalSettingsRequest request) {
            return base.Channel.ChangePortalSettings(request);
        }
        
        public void ChangePortalSettings(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.ChangePortalSettingsRequest inValue = new Appleseed.WebApi.ChangePortalSettingsRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.ChangePortalSettingsResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).ChangePortalSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appleseed.WebApi.RemovePortalResponse Appleseed.WebApi.IPortalServices.RemovePortal(Appleseed.WebApi.RemovePortalRequest request) {
            return base.Channel.RemovePortal(request);
        }
        
        public void RemovePortal(Appleseed.WebApi.AuthHeader AuthHeader) {
            Appleseed.WebApi.RemovePortalRequest inValue = new Appleseed.WebApi.RemovePortalRequest();
            inValue.AuthHeader = AuthHeader;
            Appleseed.WebApi.RemovePortalResponse retVal = ((Appleseed.WebApi.IPortalServices)(this)).RemovePortal(inValue);
        }
    }
}
